name: Build
on:
  schedule:
    - cron: '15 0/1 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run:  mvn clean install package --file pom.xml
      - name: Publish Test Report
        uses: starburstdata/action-testng-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


 



